{{- if eq (include "coog.rabbitmq.operatorMode" .) "true" }}
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: {{ printf "%s-rabbitmq-vhost" (include "general.names.short" .) }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
spec:
  name: {{ include "coog.rabbitmq.vhost" . | quote }}
  rabbitmqClusterReference:
    name: {{ .Values.rabbitmq.operator.cluster.name | quote }}
    namespace: {{ .Values.rabbitmq.operator.cluster.namespace | quote }}
{{- end }}
