{{- if .Values.paybox.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "full_name" . }}
  labels:
{{ include "chart_labels" . | indent 4 }}
spec:
  replicas: {{ .Values.paybox.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "short_name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "short_name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.paybox.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.paybox.image.repository }}:{{ .Values.paybox.image.tag }}"
          imagePullPolicy: {{ .Values.paybox.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            procMount: Default
            runAsNonRoot: true
            runAsUser: 1000
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: PAYBOX_TRYTON_URL
              value: "http://{{ .Release.Name }}-{{ .Chart.Name }}-coog"
            - name: PAYBOX_TRYTON_DB
              value: "{{ .Values.coog.postgres.database }}"
            - name: PAYBOX_TRYTON_USERNAME
              value: "{{ .Values.paybox.coog_username }}"
            - name: PAYBOX_TRYTON_PASSWORD
              value: "{{ .Values.paybox.coog_password }}"
          livenessProbe:
            tcpSocket:
              port: 3000
          readinessProbe:
            tcpSocket:
              port: 3000
          resources:
            {{- toYaml .Values.paybox.resources | nindent 12 }}
      {{- with .Values.paybox.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.paybox.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.paybox.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end -}}
