{{- if .Values.paybox.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "general.names.fullname" . }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ default .Values.replicaCount .Values.paybox.replicaCount }}
  strategy:
    type: {{ default .Values.strategy.type .Values.paybox.strategy.type }}
  selector:
    matchLabels: {{- include "general.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "general.labels.standard" . | nindent 8 }}
      annotations:
        checksum/configmap: {{ include (printf "%s/%s/%s" $.Template.BasePath (base (dir .Template.Name)) "configmap.yaml") . | sha256sum }}
        {{- if (and .Values.secrets .Values.secrets.paybox .Values.secrets.paybox.extraEnvVar) -}}
        checksum/secret: {{ include (printf "%s/%s/%s" $.Template.BasePath (base (dir .Template.Name)) "secret.yaml") . | sha256sum }}
        {{- end }}
    spec:
      imagePullSecrets:
        - name: {{ (default "docker-registry" (and .Values.imageCredentials .Values.imageCredentials.name)) }}
      containers:
        - name: {{ include "general.names.name" . }}
          image: "{{ default .Values.image.repository .Values.paybox.image.repository }}/{{ .Values.paybox.image.name }}:{{ default .Values.image.tag .Values.paybox.image.tag }}"
          imagePullPolicy: {{ default .Values.image.pullPolicy .Values.paybox.image.pullPolicy | quote }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            procMount: Default
            runAsNonRoot: true
            runAsUser: {{ default .Values.securityContext.runAsUser .Values.paybox.securityContext.runAsUser }}
            runAsGroup: {{ default .Values.securityContext.runAsGroup .Values.paybox.securityContext.runAsGroup }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-configuration" (include "general.names.fullname" .) }}
            {{- if (and .Values.secrets .Values.secrets.paybox .Values.secrets.paybox.extraEnvVar) -}}
            - secretRef:
                name: {{ printf "%s-configuration" (include "general.names.fullname" .) }}
            {{- end }}
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            tcpSocket:
              port: 3000
          readinessProbe:
            tcpSocket:
              port: 3000
          resources: {{- toYaml .Values.paybox.resources | nindent 12 }}
      {{- with default .Values.nodeSelector .Values.paybox.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with default .Values.affinity .Values.paybox.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with default .Values.tolerations .Values.paybox.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if default .Values.dnsPolicy .Values.paybox.dnsPolicy }}
      dnsPolicy: {{ default .Values.dnsPolicy .Values.paybox.dnsPolicy }}
      {{- end }}
      {{- if default .Values.dnsConfig .Values.paybox.dnsConfig }}
      dnsConfig: {{- toYaml default .Values.dnsConfig .Values.paybox.dnsConfig | indent 8 }}
      {{- end }}
{{- end }}
