apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ default .Values.replicaCount .Values.cron.replicaCount }}
  strategy:
  {{- if not .Values.quota.rollingUpdate }}
    type: Recreate
  {{- else -}}
    type: {{ default .Values.strategy.type .Values.coog.strategy.type }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
    spec:
    {{- with .Values.image.pullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.coog.persistentVolume.enabled }}
      volumes:
        - name: {{ printf "%s-%s" .Release.Name .Values.coog.persistentVolume.name | trunc 63 | trimSuffix "-" }}
          persistentVolumeClaim:
            claimname: {{ printf "%s-%s" .Release.Name .Values.coog.persistentVolume.name | trunc 63 | trimSuffix "-" }}
    {{- end }}
      containers:
        - name: {{ include "common.names.name" . }}
          image: "{{ default .Values.image.repository .Values.coog.image.repository }}/{{ .Values.coog.image.name }}:{{ default .Values.image.tag .Values.coog.image.tag }}"
          imagepullPolicy: {{ default .Values.image.pullPolicy .Values.coog.image.pullPolicy | quote }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            procMount: Default
            runAsNonRoot: true
            runAsUser: {{ default .Values.securityContext.runAsUser .Values.coog.securityContext.runAsUser }}
          command: ['ep', 'cron']
        {{- if .Values.coog.persistentVolume.enabled }}
          volumeMounts:
            - name: {{ printf "%s-%s" .Release.Name .Values.coog.persistentVolume.name | trunc 63 | trimSuffix "-" }}
              mountPath: /workspace/io
              readOnly: false
        {{- end }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-%s-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
            - configMapRef:
                name: {{ printf "%s-configuration" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
            - secretRef:
                name: {{ printf "%s-%s-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
            - secretRef:
                name: {{ printf "%s-%s-postgresql" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
          ports:
            - name: http
              containerPort: {{ .Values.coog.containerPorts.http }}
          startupProbe:
            exec:
              command: ['/bin/bash', '-c', 'ep cron --check']
            {{- toYaml (default .Values.startupProbe .Values.cron.startupProbe) | nindent 12 }}
          livenessProbe:
            exec:
              command: ['/bin/bash', '-c', 'ep cron --check']
            {{- toYaml (default .Values.livenessProbe .Values.cron.livenessProbe) | nindent 12 }}
          resources: {{- toYaml .Values.cron.resources | nindent 12 }}
      {{- with default .Values.nodeSelector .Values.cron.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with default .Values.affinity .Values.cron.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with default .Values.tolerations .Values.cron.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if default .Values.dnsPolicy .Values.cron.dnsPolicy }}
      dnsPolicy: {{ default .Values.dnsPolicy .Values.cron.dnsPolicy }}
      {{- end }}
      {{- if default .Values.dnsConfig .Values.cron.dnsConfig }}
      dnsConfig: {{- toYaml default .Values.dnsConfig .Values.cron.dnsConfig | indent 8 }}
      {{- end }}
