apiVersion: v2
name: coog-v2
version: 2.14.2344
appVersion: "coog-master"
description: A Helm chart for Coog
icon: http://coopengo.com/img/tn_coog_v2-6_edith.png
dependencies:
  - name: mongodb
    version: 12.1.31
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.isManaged
  - name: rabbitmq
    version: 12.3.0
    repository: https://charts.bitnami.com/bitnami
  - name: postgresql
    version: 11.9.11
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.isManaged
