apiVersion: v2
name: coog
version: 2.14.2344-3-v2
appVersion: coog-master
home: https://github.com/coopengo/coog-helm-charts
sources:
  - https://github.com/coopengo/coog-helm-charts
description: A Helm chart for Coog
icon: http://coopengo.com/img/tn_coog_v2-6_edith.png
dependencies:
  - name: mongodb
    version: 7.14.1
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.isManaged
  - name: rabbitmq
    version: 7.6.8
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 10.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: 8.9.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.isManaged
  - name: flower
    version: 0.2.1
    repository: https://gitlab.com/api/v4/projects/35933718/packages/helm/stable
    condition: flower.enabled
