dependencies:
- name: mongodb
  version: 7.14.1
  repository: https://charts.bitnami.com/bitnami
  condition: mongodb.enabled

- name: rabbitmq
  version: 7.6.8
  repository: https://charts.bitnami.com/bitnami
  condition: rabbitmq.enabled

- name: redis
  version: 10.5.0
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled

- name: postgresql
  version: 8.9.6
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled

- name: flower
  version: 0.2.1
  repository: https://gitlab.com/api/v4/projects/35933718/packages/helm/stable
  condition: flower.enabled

  #- name: nginx
  #version: 5.1.6
  #repository: https://charts.bitnami.com/bitnami
  #condition: nginx.enabled
