{{- if .Values.cron.enabled -}}
{{- if (and .Values.cron .Values.cron.extraEnvVar) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-configuration" (include "general.names.fullname" .) }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.cron.extraEnvVar }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
