apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ default .Values.replicaCount .Values.celery.replicaCount }}
{{- if not .Values.quota.rolling_update }}
  strategy:
    type: Recreate
{{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
    spec:
    {{- with .Values.coog.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.coog.persistentVolume.enable }}
      volumes:
        - name: {{ include "common.names.fullname" . }}-{{ .Values.coog.persistentVolume.name }}
          persistentVolumeClaim:
            claimname: {{ include "common.names.fullname" . }}-{{ .Values.coog.persistentVolume.name }}
    {{- end }}
      containers:
        - name: {{ include "common.names.name" . }}
          image: "{{ .Values.coog.image.repository }}:{{ default .Values.image.tag .Values.coog.image.tag }}"
          imagepullPolicy: {{ default .Values.image.pullPolicy .Values.coog.image.pullPolicy | quote }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            procMount: Default
            runAsNonRoot: true
            runAsUser: {{ .Values.coog.securityContext.runAsUser }}
          command:
            - ep
            - celery
            - "{{ .Values.celery.workers.number }}"
        {{- if .Values.coog.persistentVolume.enable }}
          volumeMounts:
            - name: {{ include "common.names.fullname" . }}-{{ .Values.coog.persistentVolume.name }}
              mountPath: /workspace/io
              readOnly: false
        {{- end }}
          env:
            - name:  COOG_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-%s-database" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
                  key: db-username
            - name:  COOG_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-%s-database" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
                  key: db-password
            - name:  TRYTOND_ASYNC__CELERY
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-%s-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
                  key: TRYTOND_ASYNC__CELERY
            - name:  TRYTOND_ASYNC_CELERY
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-%s-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
                  key: TRYTOND_ASYNC__CELERY
            - name:  TRYTOND_DATABASE__URI
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-%s-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
                  key: TRYTOND_DATABASE__URI
            - name:  TRYTOND_SESSION__PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-%s-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
                  key: TRYTOND_SESSION__PASSPHRASE
            - name: TRYTOND_REPORT__API
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "%s-%s-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
                  key: TRYTOND_REPORT__API
            - name: COOG_POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "%s-%s-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
                  key: COOG_POSTGRES_HOST
            - name: COOG_POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "%s-%s-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
                  key: COOG_POSTGRES_PORT
            - name: COOG_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "%s-%s-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
                  key: COOG_DB_NAME
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "%s-%s-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
                  key: COOG_DB_NAME
            - name: CELERY_MAX_MEMORY_PER_CHILD
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "%s-%s-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
                  key: CELERY_MAX_MEMORY_PER_CHILD
            {{- range $key, $value := .Values.coog.config }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "%s-%s-configuration" $.Release.Name $.Chart.Name | trunc 63 | trimSuffix "-" }}
                  key: {{ $key }}
            {{- end }}
            {{- range $key, $value := .Values.celery.config }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "%s-%s-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
                  key: {{ $key }}
            {{- end }}
            {{- range $key, $value := .Values.secrets.coog }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-%s-configuration" $.Release.Name $.Chart.Name | trunc 63 | trimSuffix "-" }}
                  key: {{ $key }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            periodSeconds: 60
            timeoutSeconds: 10
            exec:
              command:
                - "/bin/bash"
                - "-c"
                - "celery -A {{ .Values.cron.coogCeleryModule }} inspect ping -d celery@$HOSTNAME"
            {{- toYaml .Values.celery.livenessProbe | nindent 12 }}
          readinessProbe:
            periodSeconds: 30
            timeoutSeconds: 10
            exec:
              command:
                - "/bin/bash"
                - "-c"
                - "celery -A {{ .Values.cron.coogCeleryModule }} inspect ping -d celery@$HOSTNAME"
          resources:
            {{- toYaml .Values.celery.resources | nindent 12 }}
      {{- with .Values.celery.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.celery.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.celery.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- if .Values.coog.dnsPolicy }}
      dnsPolicy: {{ .Values.coog.dnsPolicy }}
{{- end }}
{{- if .Values.coog.dnsConfig }}
      dnsConfig:
{{ toYaml .Values.coog.dnsConfig | indent 8 }}
{{- end }}
