{{- if .Values.unoconv.enable -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.unoconv.service.type }}
  ports:
    - port: {{ .Values.unoconv.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
{{- end }}
