dependencies:
- name: mongodb
  version: 10.30.12
  repository: https://charts.bitnami.com/bitnami
  condition: mongodb.enable

- name: rabbitmq
  version: 8.26.3
  repository: https://charts.bitnami.com/bitnami
  condition: rabbitmq.enable

- name: postgresql
  version: 10.15.1
  repository: https://charts.bitnami.com/bitnami
  condition: postgres.isManaged

  #- name: nginx
  #version: 5.1.6
  #repository: https://charts.bitnami.com/bitnami
  #condition: nginx.enable
