apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "general.names.fullname" . }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ default .Values.replicaCount .Values.backCore.static.replicaCount }}
  strategy:
    type: {{ default .Values.strategy.type .Values.backCore.static.strategy.type }}
  selector:
    matchLabels: {{- include "general.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "general.labels.standard" . | nindent 8 }}
      annotations:
        checksum/configmap-global: {{ include (printf "%s/%s" $.Template.BasePath "configmap-global.yaml") . | sha256sum  }}
        checksum/secret-global: {{ include (printf "%s/%s" $.Template.BasePath "secret-global.yaml") . | sha256sum  }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imageCredentials.name }}
      containers:
        - name: {{ include "general.names.name" . }}
          image: "{{ default .Values.image.repository .Values.backCore.static.image.repository }}/{{ .Values.backCore.static.image.name }}:{{ default .Values.image.tag .Values.backCore.static.image.tag }}"
          imagePullPolicy: {{ default .Values.image.pullPolicy .Values.backCore.static.image.pullPolicy | quote }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            procMount: Default
            runAsNonRoot: true
            runAsUser: {{ default .Values.securityContext.runAsUser .Values.backCore.static.securityContext.runAsUser }}
          envFrom:
            {{- if .Values.extraEnvVar }}
            - configMapRef:
                name: {{ printf "%s-global-configuration" (include "general.names.short" .) }}
            {{- end }}
            - secretRef:
                name: {{ printf "%s-global-configuration" (include "general.names.short" .) }}
          ports:
            - name: http
              containerPort: 5000
          startupProbe:
            httpGet:
              path: /doc
              port: http
            {{- include "general.tplvalues.render" (dict "value" (default .Values.startupProbe .Values.backCore.static.startupProbe) "context" $) | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /doc
              port: http
            {{- include "general.tplvalues.render" (dict "value" (default .Values.livenessProbe .Values.backCore.static.livenessProbe) "context" $) | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /doc
              port: http
            {{- include "general.tplvalues.render" (dict "value" (default .Values.readinessProbe .Values.backCore.static.readinessProbe) "context" $) | nindent 12 }}
          resources: {{- toYaml .Values.backCore.static.resources | nindent 12 }}
      {{- with default .Values.nodeSelector .Values.backCore.static.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with default .Values.affinity .Values.backCore.static.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with default .Values.tolerations .Values.backCore.static.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if default .Values.dnsPolicy .Values.backCore.static.dnsPolicy }}
      dnsPolicy: {{ default .Values.dnsPolicy .Values.backCore.static.dnsPolicy }}
      {{- end }}
      {{- if default .Values.dnsConfig .Values.backCore.static.dnsConfig }}
      dnsConfig: {{- toYaml default .Values.dnsConfig .Values.backCore.static.dnsConfig | indent 8 }}
      {{- end }}
