{{- if .Values.static.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "full_name" . }}
  labels:
{{ include "chart_labels" . | indent 4 }}
spec:
  replicas: {{ .Values.static.replicaCount }}
{{- if not .Values.quota.rolling_update }}
  strategy:
    type: Recreate
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "short_name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "short_name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.static.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ include "short_name" . }}
          image: "{{ .Values.static.image.repository }}:{{ .Values.static.image.tag }}"
          imagePullPolicy: {{ .Values.static.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            procMount: Default
            runAsNonRoot: true
            runAsUser: {{ .Values.coog.securityContext.runAsUser }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /doc
              port: http
          readinessProbe:
            httpGet:
              path: /doc
              port: http
          resources:
            {{- toYaml .Values.static.resources | nindent 12 }}
      {{- with .Values.static.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.static.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.static.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- if .Values.coog.dnsPolicy }}
      dnsPolicy: {{ .Values.coog.dnsPolicy }}
{{- end }}
{{- if .Values.coog.dnsConfig }}
      dnsConfig:
{{ toYaml .Values.coog.dnsConfig | indent 8 }}
{{- end }}
{{- end }}
