{{- if .Values.static.enabled -}}
{{- if .Values.static.ingress.enabled -}}
apiVersion: {{ include "common.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
  {{- if $.Values.maintenance_mode.enabled }}
  {{- range $key, $value := $.Values.maintenance_mode.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
    nginx.ingress.kubernetes.io/custom-http-errors: {{ $.Values.maintenance_mode.ingress.nginx.customhttperrors | quote }}
    nginx.ingress.kubernetes.io/default-backend: "{{ $.Release.Name }}-{{ $.Chart.Name }}-maintenance"
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ $.Values.maintenance_mode.ingress.nginx.whitelistSourceRange | quote }}
  {{- else }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .Values.static.ingress.nginx.whitelistSourceRange | quote }}
  {{- end }}
  {{- range $key, $value := .Values.static.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
{{- if .Values.static.ingress.tls }}
  tls:
  {{- range .Values.static.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.static.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
        {{- if eq (include "common.ingress.apiVersion" $) "networking.k8s.io/v1" }}
        - path: {{ . }}
          pathType: Prefix
          backend:
            service:
              name: {{ include "common.names.fullname" . }}
              port:
                name: http
        {{- else -}}
        - path: {{ . }}
          backend:
            servicename: {{ include "common.names.fullname" . }}
            servicePort: http
        {{- end }}
        {{- end }}
  {{- end }}
{{- end }}
{{- end }}
