apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configuration
  labels:
{{ include "chart_labels" . | indent 4 }}
data:
  config.conf: |-
    TRYTOND_REPORT__API = http://{{ .Release.Name }}-{{ .Chart.Name }}-unoconv:5000/unoconv/{oext}
    COOG_POSTGRES_HOST = {{ .Values.postgres.host }}
    COOG_POSTGRES_PORT = {{ .Values.postgres.port }}
    COOG_DB_NAME = {{ .Values.secrets.coog.postgres.database }}
    {{- range $key, $val := .Values.coog.config }}
    {{ $key }} = {{ $val }}
    {{- end }}
