apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configuration
  labels:
{{ include "chart_labels" . | indent 4 }}
data:
  config.conf: |-
    TRYTOND_REPORT__API = http://{{ .Release.Name }}-{{ .Chart.Name }}-unoconv:5000/unoconv/{oext}
    COOG_POSTGRES_HOST = {{ .Values.postgresql.host }}
    COOG_POSTGRES_PORT = {{ .Values.postgresql.service.ports.postgresql }}
    COOG_DB_NAME = {{ .Values.postgresql.auth.database }}
    {{- range $key, $value := .Values.coog.config }}
    {{ $key }} = {{ $value }}
    {{- end }}
