apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-configuration" (include "general.names.short" .) }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
data:
  COOG_SERVER_WORKERS: {{ default .Values.backCore.workers.number .Values.backCore.coog.workers.number | quote }}
  TRYTOND_WEB__CORS: {{ include "backcore.coog.cors" . | quote }}
  {{- if (or .Values.customerBackend.enabled .Values.customerFrontend.enabled) }}
  TRYTOND_STRAPI__URL: {{ printf "http://%s-customer-backend" (include "general.names.short" .) | quote }}
  {{- end }}
  {{- range $key, $value := .Values.backCore.coog.extraEnvVar }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
