{{- if or .Values.podDisruptionBudget .Values.backCore.coog.podDisruptionBudget }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ printf "%s" (include "general.names.short" .) }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "general.labels.matchLabels" . | nindent 6 }}
  {{- if or .Values.podDisruptionBudget.minAvailable .Values.backCore.coog.podDisruptionBudget.minAvailable }}
  minAvailable: {{ default .Values.podDisruptionBudget.minAvailable .Values.backCore.coog.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if or .Values.podDisruptionBudget.maxUnavailable .Values.backCore.coog.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ default .Values.podDisruptionBudget.maxUnavailable .Values.backCore.coog.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}