{{- if .Values.secrets.backCore.coog.config -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.backCore.coog.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
