{{- if and .Values.backCore.persistentVolume.enabled .Values.backCore.persistentVolume.customStorageClass -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ required ".Values.backCore.persistentVolume.storageClass is required when using customStorageClass!" .Values.backCore.persistentVolume.storageClass }}
{{- toYaml .Values.backCore.persistentVolume.customStorageClass | nindent 0 }}
{{- end -}}