apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ default .Values.replicaCount .Values.coog.replicaCount }}
  {{- if not .Values.quota.rolling_update }}
  strategy:
    type: Recreate
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
    spec:
    {{- with .Values.coog.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.coog.persistentVolume.enabled }}
      volumes:
        - name: {{ include "common.names.fullname" . }}-{{ .Values.coog.persistentVolume.name }}
          persistentVolumeClaim:
            claimname: {{ include "common.names.fullname" . }}-{{ .Values.coog.persistentVolume.name }}
        - name: {{ include "common.names.fullname" . }}-configuration
          configMap:
            name: {{ include "common.names.fullname" . }}-configuration
      {{- end }}
      initContainers:
        - name: {{ .Chart.Name }}-module-update
          image: "{{ .Values.coog.image.repository }}:{{ default .Values.image.tag .Values.coog.image.tag }}"
          imagepullPolicy: {{ default .Values.image.pullPolicy .Values.coog.image.pullPolicy | quote }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            procMount: Default
            runAsNonRoot: true
            runAsUser: {{ .Values.coog.securityContext.runAsUser }}
          resources:
            {{- toYaml .Values.coog.initContainers.resources | nindent 12 }}
          command: ['sh', '-c', 'ep admin -cu ir res --activate-dependencies']
          env:
            {{- if .Values.coog.extraEnv }}
            {{- range $key, $value := .Values.coog.extraEnv }}
            - name:  {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            - name:  COOG_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-%s" .Release.Name "db"  }}
                  key: db-username
            - name:  COOG_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-%s" .Release.Name "db"  }}
                  key: db-password
            - name:  TRYTOND_ASYNC__CELERY
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-%s" .Release.Name "coog"  }}
                  key: TRYTOND_ASYNC__CELERY
            - name:  TRYTOND_ASYNC_CELERY
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-%s" .Release.Name "coog"  }}
                  key: TRYTOND_ASYNC__CELERY
            - name:  TRYTOND_DATABASE__URI
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-%s" .Release.Name "coog"  }}
                  key: TRYTOND_DATABASE__URI
            {{- range $key, $value := .Values.secrets.coog }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-%s" .Release.Name "coog"  }}
                  key: {{ $key }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
      containers:
        - name: {{ include "common.names.name" . }}
          image: "{{ .Values.coog.image.repository }}:{{ default .Values.image.tag .Values.coog.image.tag }}"
          imagepullPolicy: {{ default .Values.image.pullPolicy .Values.coog.image.pullPolicy | quote }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            procMount: Default
            runAsNonRoot: true
            runAsUser: {{ .Values.coog.securityContext.runAsUser }}
          command:
            - ep
            - server
            - "{{ .Values.coog.workers }}"
          volumeMounts:
            {{- if .Values.coog.persistentVolume.enabled }}
            - name: {{ include "common.names.fullname" . }}-{{ .Values.coog.persistentVolume.name }}
              mountPath: /workspace/io
              readOnly: false
            {{- end }}
            {{- if .Values.coog.configurationFiles }}
            {{- range $key, $val := .Values.coog.configurationFiles }}
            - name: {{ $.Release.Name }}-configuration
              mountPath: /workspace/{{ $key }}
              subPath: {{ $key }}
            {{- end }}
            {{- end }}
          env:
            {{- if .Values.coog.extraEnv }}
            {{- range $key, $value := .Values.coog.extraEnv }}
            - name:  {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            - name:  COOG_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-%s" .Release.Name "db"  }}
                  key: db-username
            - name:  COOG_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-%s" .Release.Name "db"  }}
                  key: db-password
            - name:  TRYTOND_ASYNC__CELERY
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-%s" .Release.Name "coog"  }}
                  key: TRYTOND_ASYNC__CELERY
            - name:  TRYTOND_ASYNC_CELERY
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-%s" .Release.Name "coog"  }}
                  key: TRYTOND_ASYNC__CELERY
            - name:  TRYTOND_DATABASE__URI
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-%s" .Release.Name "coog"  }}
                  key: TRYTOND_DATABASE__URI
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /liveness
              port: http
            exec:
              {{- toYaml .Values.coog.livenessProbe | nindent 12 }}
          readinessProbe:
            httpGet:
              path: "/{{ .Values.postgres.auth.database }}/readiness"
              port: http
            exec:
              {{- toYaml .Values.coog.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.coog.resources | nindent 12 }}
      {{- with .Values.coog.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.coog.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.coog.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- if .Values.coog.dnsPolicy }}
      dnsPolicy: {{ .Values.coog.dnsPolicy }}
{{- end }}
{{- if .Values.coog.dnsConfig }}
      dnsConfig:
{{ toYaml .Values.coog.dnsConfig | indent 8 }}
{{- end }}