{{- if .Values.customer_frontend.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: coog-customer-frontend-configuration
  labels:
{{ include "chart_labels" . | indent 4 }}
type: Opaque
stringData:
  GATSBY_GEOAPIFY_API_KEY: {{ .Values.secrets.customer_frontend.gatsby_geoapify_api_key | quote }}
{{- end }}
