{{- if .Values.customerFrontend.enabled -}}
{{- if .Values.secrets.customerFrontend.extraEnvVar -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-configuration" (include "general.names.fullname" .) }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.customerFrontend.extraEnvVar }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
