apiVersion: v1
kind: Secret
metadata:
  name: {{ include "full_name" . }}-postgres-secret
  labels:
{{ include "chart_labels" . | indent 4 }}
type: Opaque
stringData:
  USER: {{ .Values.coog.postgres.user | quote }}
  PASSWORD: {{ .Values.coog.postgres.password | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "full_name" . }}-coog-web-secret
  labels:
{{ include "chart_labels" . | indent 4 }}
type: Opaque
stringData:
  GATEWAY_TOKEN: {{ .Values.gateway.coog_web_token | quote }}
  CUSTOMER_BACKEND_TOKEN: {{ .Values.customer_backend.coog_web_token | quote }}