{{- if (and .Values.secrets .Values.secrets.backCore .Values.secrets.backCore.cron .Values.secrets.backCore.cron.extraEnvVar) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-cron-configuration" (include "general.names.short" .) }}
  labels:
    {{- $defaultLabels := include "general.labels.standard" . | fromYaml }}
    {{- $customName := printf "%s-%s" .Chart.Name "cron" }}
    {{- $nameLabel := dict "app.kubernetes.io/name" $customName }}
    {{- mustMergeOverwrite $defaultLabels $nameLabel | toYaml | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := (and .Values.secrets .Values.secrets.backCore .Values.secrets.backCore.cron .Values.secrets.backCore.cron.extraEnvVar) }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
