apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-cron" (include "general.names.short" .) }}
  labels: 
    {{- $defaultLabels := include "general.labels.standard" . | fromYaml }}
    {{- $customName := printf "%s-%s" .Chart.Name "cron" }}
    {{- $nameLabel := dict "app.kubernetes.io/name" $customName }}
    {{- mustMergeOverwrite $defaultLabels $nameLabel | toYaml | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector: 
    {{- $defaultLabels := include "general.labels.matchLabels" . | fromYaml }}
    {{- $customName := printf "%s-%s" .Chart.Name "cron" }}
    {{- $nameLabel := dict "app.kubernetes.io/name" $customName }}
    {{- mustMergeOverwrite $defaultLabels $nameLabel | toYaml | nindent 3 }}

