{{- if .Values.celery.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "full_name" . }}-daily
  labels:
{{ include "chart_labels" . | indent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.celery.batch.schedule }}
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
        {{- with .Values.coog.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          restartPolicy: Never
        {{- if .Values.coog.persistentVolume.enabled }}
          volumes:
            - name: {{ .Release.Name }}-{{ .Values.coog.persistentVolume.name }}
              persistentVolumeClaim:
                claimName: {{ .Release.Name }}-{{ .Values.coog.persistentVolume.name }}
        {{- end }}
          containers:
            - name: {{ .Chart.Name }}-daily
              image: "{{ .Values.coog.image.repository }}:{{ .Values.coog.image.tag }}"
              imagePullPolicy: {{ .Values.coog.image.pullPolicy }}
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - ALL
                privileged: false
                procMount: Default
                runAsNonRoot: true
                runAsUser: {{ .Values.coog.securityContext.runAsUser }}
              command:
                - ep
                - daily
                - "4"
                - french_work_days
            {{- if .Values.coog.persistentVolume.enabled }}
              volumeMounts:
                - name: {{ .Release.Name }}-{{ .Values.coog.persistentVolume.name }}
                  mountPath: {{ .Values.coog.root_dir }}
                  readOnly: false
            {{- end }}
              env:
                - name:  COOG_SERVER_WORKERS
                  value: "{{ .Values.coog.workers }}"
                - name:  COOG_CELERY_WORKERS
                  value: "{{ .Values.coog.workers }}"
                - name:  COOG_TIMEOUT
                  value: "{{ .Values.coog.timeout }}"
                - name:  LOG_LEVEL
                  value: "{{ .Values.coog.log_level }}"
                - name:  COOG_REDIS_HOST
                  {{- if .Values.redis.enabled }}
                  value: "{{ .Release.Name }}-redis-master"
                  {{- else }}
                  value: {{ .Values.externalRedis.host | quote }}
                  {{- end }}
                - name:  COOG_REDIS_PORT
                  {{- if .Values.redis.enabled }}
                  value: "{{ .Values.redis.redisPort }}"
                  {{- else }}
                  value: {{ .Values.externalRedis.port | quote }}
                  {{- end }}
                - name:  COOG_POSTGRES_HOST
                {{- if not .Values.coog.external_postgres.enabled }}
                  value: "{{ .Release.Name }}-postgresql"
                {{ else }}
                  value: "{{ .Values.coog.external_postgres.host }}"
                {{- end }}
                - name:  COOG_POSTGRES_PORT
                {{- if not .Values.coog.external_postgres.enabled }}
                  value: "{{ .Values.postgresql.service.port }}"
                {{ else }}
                  value: "{{ .Values.coog.external_postgres.port }}"
                {{- end }}
                - name:  COOG_DB_NAME
                  value: "{{ .Values.coog.postgres.database}}"
                - name:  COOG_DB_USER
                  value: "{{ .Values.coog.postgres.user }}"
                - name:  COOG_DB_PASSWORD
                  value: "{{ .Values.coog.postgres.password }}"
                {{- if .Values.coog.extraEnv }}
                {{- range $key, $value := .Values.coog.extraEnv }}
                - name:  {{ $key }}
                  value: {{ $value | quote }}
                {{- end }}
                {{- end }}
                - name:  TRYTOND_ASYNC__CELERY
                  {{- if .Values.redis.enabled }}
                  value: "redis://{{ .Release.Name }}-redis-master:{{ .Values.redis.redisPort }}/1"
                  {{- else }}
                  value: "redis://{{ .Values.externalRedis.host }}:{{ .Values.externalRedis.port }}/1"
                  {{- end }}
                - name:  TRYTOND_ASYNC_CELERY
                  {{- if .Values.redis.enabled }}
                  value: "redis://{{ .Release.Name }}-redis-master:{{ .Values.redis.redisPort }}/1"
                  {{- else }}
                  value: "redis://{{ .Values.externalRedis.host }}:{{ .Values.externalRedis.port }}/1"
                  {{- end }}
                - name:  TRYTOND_CACHE__CLASS
                  value: "trytond.cache.SerializableMemoryCache"
                - name:  TRYTOND_CACHE__CLEAN_TIMEOUT
                  value: "0"
                - name:  TRYTOND_CACHE__URI
                  {{- if .Values.redis.enabled }}
                  value: "redis://{{ .Release.Name }}-redis-master:{{ .Values.redis.redisPort }}/0"
                  {{- else }}
                  value: "redis://{{ .Values.externalRedis.host }}:{{ .Values.externalRedis.port }}/0"
                  {{- end }}
                - name:  TRYTOND_DATABASE__URI
                {{- if not .Values.coog.external_postgres.enabled }}
                  value: "postgresql://postgres:{{ .Values.coog.postgres.password }}@{{ .Release.Name }}-postgresql:{{ .Values.postgresql.service.port }}/{{ .Values.coog.postgres.database}}"
                {{ else }}
                  value: "postgresql://{{ .Values.coog.postgres.user }}:{{ .Values.coog.postgres.password }}@{{ .Values.coog.external_postgres.host }}:{{ .Values.coog.external_postgres.port }}/{{ .Values.coog.postgres.database}}"
                {{ end }}
                - name:  TRYTOND_DEBUG__VIEWS
                  value: "False"
                - name:  TRYTOND_DEBUG__DISABLE_SYNTAX_ANALYSIS
                  value: "True"
                - name: TRYTOND_EMAIL__URI
                  value: "{{ .Values.coog.email_uri }}"
                - name: TRYTOND_EMAIL__FROM
                  value: "{{ .Values.coog.email_from }}"
                - name: TRYTOND_REPORT__API
                  value: "http://{{ .Release.Name }}-{{ .Chart.Name }}-unoconv:5000/unoconv/{oext}"
                - name: DB_NAME
                  value: "{{ .Values.coog.postgres.database }}"
                {{- if .Values.celery.batchConfig }}
                {{- range $key, $value := .Values.celery.batchConfig }}
                - name:  {{ $key }}
                  value: {{ $value | quote }}
                {{- end }}
                {{- end }}
              - name: TRYTOND_DATABASE__LANGUAGE
                value: fr
              resources:
{{ toYaml .Values.celery.cron.resources | indent 16 }}
{{- end }}
