{{- if .Values.secrets.backCore.celery.config -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-configuration" (include "common.names.fullname" .)| trunc 63 | trimSuffix "-" }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.backCore.celery.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}

