{{- if .Values.celery.enabled -}}
{{- if .Values.celery.specificBatchConcurrency.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "full_name" . }}-single"
  labels:
{{ include "chart_labels" . | indent 4 }}
spec:
  replicas: 1
{{- if not .Values.quota.rolling_update }}
  strategy:
    type: Recreate
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "short_name" . }}-single"
      app.kubernetes.io/instance: "{{ .Release.Name }}-single"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include "short_name" . }}-single"
        app.kubernetes.io/instance: "{{ .Release.Name }}-single"
    spec:
    {{- with .Values.coog.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.coog.persistentVolume.enabled }}
      volumes:
        - name: {{ .Release.Name }}-{{ .Values.coog.persistentVolume.name }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-{{ .Values.coog.persistentVolume.name }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.coog.image.repository }}:{{ .Values.coog.image.tag }}"
          imagePullPolicy: {{ .Values.coog.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            procMount: Default
            runAsNonRoot: true
            runAsUser: {{ .Values.coog.securityContext.runAsUser }}
          command:
            - ep
            - celery_single
        {{- if .Values.coog.persistentVolume.enabled }}
          volumeMounts:
            - name: {{ .Release.Name }}-{{ .Values.coog.persistentVolume.name }}
              mountPath: {{ .Values.coog.root_dir }}
              readOnly: false
        {{- end }}
          env:
            - name:  COOG_SERVER_WORKERS
              value: "{{ .Values.coog.workers }}"
            - name:  COOG_CELERY_WORKERS
              value: "{{ .Values.celery.workers }}"
            - name:  CELERY_MAX_MEMORY_PER_CHILD
              value: "{{ .Values.coog.max_worker_memory }}"
            - name:  COOG_TIMEOUT
              value: "{{ .Values.coog.timeout }}"
            - name:  LOG_LEVEL
              value: "{{ .Values.coog.log_level }}"
            {{- if not .Values.rabbitmq.enabled }}
            - name:  COOG_REDIS_HOST
              {{- if .Values.redis.enabled }}
              value: "{{ .Release.Name }}-redis-master"
              {{- else }}
              value: {{ .Values.externalRedis.host | quote }}
              {{- end }}
            - name:  COOG_REDIS_PORT
              {{- if .Values.redis.enabled }}
              value: "{{ .Values.redis.redisPort }}"
              {{- else }}
              value: {{ .Values.externalRedis.port | quote }}
              {{- end }}
            - name:  TRYTOND_CACHE__URI
              {{- if .Values.redis.enabled }}
              value: "redis://{{ .Release.Name }}-redis-master:{{ .Values.redis.redisPort }}/0"
              {{- else }}
              value: "redis://{{ .Values.externalRedis.host }}:{{ .Values.externalRedis.port }}/0"
              {{- end }}
            {{- end }}
            - name:  COOG_POSTGRES_HOST
            {{- if not .Values.coog.external_postgres.enabled }}
              value: "{{ .Release.Name }}-postgresql"
            {{ else }}
              value: "{{ .Values.coog.external_postgres.host }}"
            {{- end }}
            - name:  COOG_POSTGRES_PORT
            {{- if not .Values.coog.external_postgres.enabled }}
              value: "{{ .Values.postgresql.service.port }}"
            {{ else }}
              value: "{{ .Values.coog.external_postgres.port }}"
            {{- end }}
            - name:  COOG_DB_NAME
              value: "{{ .Values.secrets.coog.postgres.database }}"
            - name:  COOG_DB_USER
              valueFrom:
                secretKeyRef:
                  name: coog-postgres-db-secret
                  key: USER
            - name:  COOG_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: coog-postgres-db-secret
                  key: PASSWORD
            {{- if .Values.coog.extraEnv }}
            {{- range $key, $value := .Values.coog.extraEnv }}
            - name:  {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            - name: TRYTOND_CACHE__RECORD
              value: "{{ .Values.coog.cache_record }}"
            {{- if .Values.rabbitmq.enabled }}
            - name:  TRYTOND_ASYNC_CELERY
              valueFrom:
                secretKeyRef:
                  name: coog-trytond-secret
                  key: TRYTOND_ASYNC__CELERY
            - name:  TRYTOND_ASYNC__CELERY
              valueFrom:
                secretKeyRef:
                  name: coog-trytond-secret
                  key: TRYTOND_ASYNC__CELERY
            {{- end }}
            - name:  TRYTOND_CACHE__CLEAN_TIMEOUT
              value: "0"
            - name:  TRYTOND_DATABASE__URI
              valueFrom:
                secretKeyRef:
                  name: coog-trytond-secret
                  key: TRYTOND_DATABASE__URI
            - name:  TRYTOND_DEBUG__VIEWS
              value: "False"
            - name:  TRYTOND_DEBUG__DISABLE_SYNTAX_ANALYSIS
              value: "True"
            {{- if .Values.secrets.coog.email_uri }}
            - name: TRYTOND_EMAIL__URI
              valueFrom:
                secretKeyRef:
                  name: coog-trytond-secret
                  key: TRYTOND_EMAIL__URI
            {{- end }}
            {{- if .Values.secrets.coog.trytond_session__passphrase }}
            - name: TRYTOND_SESSION__PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: coog-trytond-secret
                  key: TRYTOND_SESSION__PASSPHRASE
            {{- end }}
            {{- if .Values.secrets.coog.trytond_reset_password_api__password_token_secret }}
            - name: TRYTOND_RESET_PASSWORD_API__PASSWORD_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: coog-trytond-secret
                  key: TRYTOND_RESET_PASSWORD_API__PASSWORD_TOKEN_SECRET
            {{- end }}
            {{- if .Values.secrets.coog.trytond_prest_ij__access_key }}
            - name: TRYTOND_PREST_IJ__ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: coog-trytond-secret
                  key: TRYTOND_PREST_IJ__ACCESS_KEY
            {{- end }}
            {{- if .Values.secrets.coog.trytond_document_api__document_token_secret }}
            - name: TRYTOND_DOCUMENT_API__DOCUMENT_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: coog-trytond-secret
                  key: TRYTOND_DOCUMENT_API__DOCUMENT_TOKEN_SECRET
            {{- end }}
            {{- if .Values.secrets.coog.trytond_batch_report__uri }}
            - name: TRYTOND_BATCH_REPORT__URI
              valueFrom:
                secretKeyRef:
                  name: coog-trytond-secret
                  key: TRYTOND_BATCH_REPORT__URI
            {{- end }}
            {{- if .Values.secrets.coog.trytond_paybox__secret }}
            - name: TRYTOND_PAYBOX__SECRET
              valueFrom:
                secretKeyRef:
                  name: coog-trytond-secret
                  key: TRYTOND_PAYBOX__SECRET
            {{- end }}
            {{- if .Values.secrets.coog.trytond_primotexto__key }}
            - name: TRYTOND_PRIMOTEXTO__KEY
              valueFrom:
                secretKeyRef:
                  name: coog-trytond-secret
                  key: TRYTOND_PRIMOTEXTO__KEY
            {{- end }}
            {{- if .Values.secrets.coog.trytond_migration__password }}
            - name: TRYTOND_MIGRATION__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: coog-trytond-secret
                  key: TRYTOND_MIGRATION__PASSWORD
            {{- end }}
            - name: TRYTOND_EMAIL__FROM
              value: "{{ .Values.coog.email_from }}"
            - name: TRYTOND_REPORT__API
              value: "http://{{ .Release.Name }}-{{ .Chart.Name }}-unoconv:5000/unoconv/{oext}"
            - name: DB_NAME
              value: "{{ .Values.secrets.coog.postgres.database }}"
            - name: TRYTOND_BATCH_CONTRACT_INVOICE_BULK___SET___NUMBER__JOB_SIZE
              value: "1"
            - name: TRYTOND_CONCURRENCY_CONTRACT_INVOICE_BULK___SET___NUMBER
              value: "1"
            {{- if .Values.celery.batchConfig }}
            {{- range $key, $value := .Values.celery.batchConfig }}
            - name:  {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            periodSeconds: 30
            timeoutSeconds: 10
            exec:
              command:
                - "/bin/bash"
                - "-c"
                - "celery -A {{ .Values.cron.coogCeleryModule }} inspect ping -d celery@$HOSTNAME"
            {{- toYaml .Values.celery.livenessProbe | nindent 12 }}
          readinessProbe:
            periodSeconds: 30
            timeoutSeconds: 10
            exec:
              command:
                - "/bin/bash"
                - "-c"
                - "celery -A {{ .Values.cron.coogCeleryModule }} inspect ping -d celery@$HOSTNAME"
          resources:
            {{- toYaml .Values.celery.specificBatchConcurrency.resources | nindent 12 }}
      {{- with .Values.celery.specificBatchConcurrency.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.celery.specificBatchConcurrency.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.celery.specificBatchConcurrency.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end -}}
{{- end }}
