{{- if .Values.app_b2c.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ default .Values.replicaCount .Values.app_b2c.replicaCount }}
{{- if not .Values.quota.rolling_update }}
  strategy:
    type: Recreate
{{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
    spec:
    {{- with .Values.app_b2c.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ include "common.names.name" . }}
          image: "{{ .Values.app_b2c.image.repository }}:{{ default .Values.image.tag .Values.app_b2c.image.tag }}"
          imagepullPolicy: {{ default .Values.image.pullPolicy .Values.app_b2c.image.pullPolicy | quote }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            procMount: Default
            runAsNonRoot: true
            runAsUser: {{ .Values.coog.securityContext.runAsUser }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.app_b2c.resources | nindent 12 }}
      {{- with .Values.app_b2c.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.app_b2c.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.app_b2c.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- if .Values.app_b2c.dnsPolicy }}
      dnsPolicy: {{ .Values.app_b2c.dnsPolicy }}
{{- end }}
{{- if .Values.app_b2c.dnsConfig }}
      dnsConfig:
{{ toYaml .Values.app_b2c.dnsConfig | indent 8 }}
{{- end -}}
{{- end }}
