{{- if .Values.appB2c.enable -}}
{{- if .Values.appB2c.ingress.enable -}}
apiVersion: {{ include "common.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- with .Values.appB2c.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.appB2c.ingress.tls }}
  tls:
  {{- range .Values.appB2c.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.appB2c.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
        {{- if eq (include "common.ingress.apiVersion" $) "networking.k8s.io/v1" }}
        - path: {{ . }}
          pathType: Prefix
          backend:
            service:
              name: {{ include "common.names.fullname" . }}
              port:
                name: http
        {{- else -}}
        - path: {{ . }}
          backend:
            servicename: {{ include "common.names.fullname" . }}
            servicePort: http
        {{- end }}
        {{- end }}
  {{- end }}
{{- end }}
{{- end }}
