{{- if (or .Values.frontCore.enabled
          .Values.apiB2c.enabled
          .Values.apiReferential.enabled
          .Values.b2c.enabled
          .Values.b2b.enabled
          .Values.customerBackend.enabled
          .Values.customerFrontend.enabled
          .Values.web.enabled)
-}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s-frontcore-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
data:
  # Databases
  MONGO_HOST: {{ default (printf "%s-mongodb" .Release.Name) .Values.mongodb.host | quote }}
  MONGO_PORT: {{ .Values.mongodb.service.ports.mongodb | quote }}
  MONGO_DB_NAME: {{ .Values.mongodb.auth.database | quote }}
  COOG_DB_NAME: {{ default .Release.Name .Values.postgresql.auth.database | quote }}
  COOG_URL: {{ printf "http://%s-%s" .Release.Name .Chart.Name | quote }}
  {{- range $key, $value := .Values.frontCore.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}