{{- if .Values.extraEnvVar }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s-global-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.extraEnvVar }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
