apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ default .Values.replicaCount .Values.backCore.coog.replicaCount }}
  strategy:
  {{- if not .Values.quota.rollingUpdate }}
    type: Recreate
  {{- else -}}
    type: {{ default .Values.strategy.type .Values.backCore.coog.strategy.type }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imageCredentials.name }}
    {{- if .Values.backCore.coog.persistentVolume.enabled }}
      volumes:
        - name: {{ printf "%s-%s" .Release.Name .Values.backCore.coog.persistentVolume.name | trunc 63 | trimSuffix "-" }}
          persistentVolumeClaim:
            claimname: {{ printf "%s-%s" .Release.Name .Values.backCore.coog.persistentVolume.name | trunc 63 | trimSuffix "-" }}
      {{- end }}
      initContainers:
        - name: {{ printf "%s-module-update" (include "common.names.name" .) | trunc 63 | trimSuffix "-" }}
          image: "{{ default .Values.image.repository .Values.backCore.coog.image.repository }}/{{ .Values.backCore.coog.image.name }}:{{ default .Values.image.tag .Values.backCore.coog.image.tag }}"
          imagepullPolicy: {{ default .Values.image.pullPolicy .Values.backCore.coog.image.pullPolicy | quote }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            procMount: Default
            runAsNonRoot: true
            runAsUser: {{ default .Values.securityContext.runAsUser .Values.backCore.coog.securityContext.runAsUser }}
          command: ['sh', '-c', 'ep admin -cu ir res --activate-dependencies']
          envFrom:
            {{- if .Values.config }}
            - configMapRef:
                name: {{ printf "%s-%s-global-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
            {{- end }}
            {{- if .Values.backCore.config }}
            - configMapRef:
                name: {{ printf "%s-%s-backCore-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
            {{- end }}
            - configMapRef:
                name: {{ printf "%s-%s-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
            {{- if .Values.secrets.config }}
            - secretRef:
                name: {{ printf "%s-%s-global-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
            {{- end }}
            {{- if .Values.secrets.backCore.config }}
            - secretRef:
                name: {{ printf "%s-%s-backCore-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
            {{- end }}
            - secretRef:
                name: {{ printf "%s-%s-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
            - secretRef:
                name: {{ printf "%s-%s-postgresql" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
          ports:
            - name: http
              containerPort: 8000
          resources: {{- toYaml .Values.backCore.coog.initContainers.resources | nindent 12 }}
      containers:
        - name: {{ include "common.names.name" . }}
          image: "{{ default .Values.image.repository .Values.backCore.coog.image.repository }}/{{ .Values.backCore.coog.image.name }}:{{ default .Values.image.tag .Values.backCore.coog.image.tag }}"
          imagepullPolicy: {{ default .Values.image.pullPolicy .Values.backCore.coog.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            procMount: Default
            runAsNonRoot: true
            runAsUser: {{ default .Values.securityContext.runAsUser .Values.backCore.coog.securityContext.runAsUser }}
          command: ['ep', 'server', '{{ default .Values.backCore.workers.number .Values.backCore.coog.workers.number }}']
          {{- if or .Values.backCore.coog.persistentVolume.enabled .Values.backCore.coog.configurationFiles }}
          volumeMounts:
            {{- if .Values.backCore.coog.persistentVolume.enabled }}
            - name: {{ printf "%s-%s" .Release.Name .Values.backCore.coog.persistentVolume.name | trunc 63 | trimSuffix "-" }}
              mountPath: /workspace/io
              readOnly: false
            {{- end }}
            {{- if .Values.backCore.coog.configurationFiles }}
            {{- range $key, $val := .Values.backCore.coog.configurationFiles }}
            - name: {{ printf "%s-configuration" $.Release.Name | trunc 63 | trimSuffix "-" }}
              mountPath: /workspace/{{ $key }}
              subPath: {{ $key }}
            {{- end }}
            {{- end }}
          {{- end }}
          envFrom:
            {{- if .Values.config }}
            - configMapRef:
                name: {{ printf "%s-%s-global-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
            {{- end }}
            {{- if .Values.backCore.config }}
            - configMapRef:
                name: {{ printf "%s-%s-backCore-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
            {{- end }}
            - configMapRef:
                name: {{ printf "%s-%s-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
            {{- if .Values.secrets.config }}
            - secretRef:
                name: {{ printf "%s-%s-global-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
            {{- end }}
            {{- if .Values.secrets.backCore.config }}
            - secretRef:
                name: {{ printf "%s-%s-backCore-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
            {{- end }}
            - secretRef:
                name: {{ printf "%s-%s-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
            - secretRef:
                name: {{ printf "%s-%s-postgresql" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
          ports:
            - name: http
              containerPort: 8000
          startupProbe: {{- toYaml (default .Values.startupProbe .Values.backCore.coog.startupProbe) | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /liveness
              port: http
            {{- toYaml (default .Values.livenessProbe .Values.backCore.coog.livenessProbe) | nindent 12 }}
          readinessProbe:
            httpGet:
              path: "/{{ .Values.postgresql.auth.database }}/readiness"
              port: http
            {{- toYaml (default .Values.readinessProbe .Values.backCore.coog.readinessProbe) | nindent 12 }}
          resources: {{- toYaml .Values.backCore.coog.resources | nindent 12 }}
      {{- with default .Values.nodeSelector .Values.backCore.coog.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with default .Values.affinity .Values.backCore.coog.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with default .Values.tolerations .Values.backCore.coog.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if default .Values.dnsPolicy .Values.backCore.coog.dnsPolicy }}
      dnsPolicy: {{ default .Values.dnsPolicy .Values.backCore.coog.dnsPolicy }}
      {{- end }}
      {{- if default .Values.dnsConfig .Values.backCore.coog.dnsConfig }}
      dnsConfig: {{- toYaml default .Values.dnsConfig .Values.backCore.coog.dnsConfig | indent 8 }}
      {{- end }}