{{- if and .Values.backCore.persistentVolume.enabled (not .Values.backCore.persistentVolume.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-%s" .Release.Name .Values.backCore.persistentVolume.name | trunc 63 | trimSuffix "-" }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
spec:
  accessModes:
  {{- range .Values.backCore.persistentVolume.accessModes }}
    - {{ . | quote }}
  {{- end }}
  storageClassName: {{ default "" .Values.backCore.persistentVolume.storageClass | quote }}
  {{- if .Values.backCore.persistentVolume.existingClaim }}
  volumeName: {{ .Values.backCore.persistentVolume.existingClaim }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backCore.persistentVolume.size }}
{{- end -}}
