{{- if .Values.quota.enabled -}}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "general.names.fullname" . }}
  namespace: {{ .Release.Name }}
spec:
  hard:
    requests.cpu: {{ .Values.quota.config.cpuRequest }}
    requests.memory: {{ .Values.quota.config.memoryRequest }}
    limits.cpu: {{ .Values.quota.config.cpuLimit }}
    limits.memory: {{ .Values.quota.config.memoryLimit }}
{{- end }}
