{{- if .Values.quota.enabled -}}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "general.names.fullname" . }}
  namespace: {{ .Release.Name }}
spec:
  hard:
    requests.cpu: {{ .Values.quota.extraEnvVar.cpuRequest }}
    requests.memory: {{ .Values.quota.extraEnvVar.memoryRequest }}
    limits.cpu: {{ .Values.quota.extraEnvVar.cpuLimit }}
    limits.memory: {{ .Values.quota.extraEnvVar.memoryLimit }}
{{- end }}
