---
{{- if and .Values.istio.enabled }}
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: {{ printf "%s-rabbitmq-idle-timeout" $.Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
spec:
  host: {{ include "coog.rabbitmq.hostFqdn" . }}
  trafficPolicy:
    {{- include "general.tplvalues.render" (dict "value" (.Values.rabbitmq.istio.trafficPolicy) "context" $) | nindent 4 }}

{{- end }}
