{{- if (or .Values.frontCore.enabled
          .Values.apiB2c.enabled
          .Values.apiReferential.enabled
          .Values.b2c.enabled
          .Values.b2b.enabled
          .Values.customerBackend.enabled
          .Values.customerFrontend.enabled)
-}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-mongodb-configuration" (include "general.names.short" .) }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  MONGODB_URI: {{ include "mongodb.uri" . | quote }}
{{- end }}
