{{- if (or .Values.frontCore.enabled
          .Values.apiB2c.enabled
          .Values.apiReferential.enabled
          .Values.b2c.enabled
          .Values.b2b.enabled
          .Values.customerBackend.enabled
          .Values.customerFrontend.enabled
          .Values.web.enabled)
-}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-mongodb-configuration" (include "general.names.short" .) }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.mongodb.uriEnabled }}
  MONGODB_URI: {{ include "mongodb.uri" . | quote }}
  {{- else }}
  MONGO_USER: {{ default "" (first .Values.mongodb.auth.usernames) }}
  MONGO_HOST: {{ printf "%s-mongodb" .Release.Name }}
  MONGO_PASSWORD: {{ default "" (first .Values.mongodb.auth.passwords) }}
  {{- end }}
{{- end }}
