{{- if (and .Values.imageCredentials .Values.imageCredentials.registry .Values.imageCredentials.username .Values.imageCredentials.password .Values.imageCredentials.email) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ (default "docker-registry" (and .Values.imageCredentials .Values.imageCredentials.name)) }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}