{{- if .Values.secrets.config }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s-global-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
