apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-backcore-configuration" (include "general.names.short" .) }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  TRYTOND_DATABASE__URI: "postgresql://{{ default "" .Values.postgresql.auth.username }}:{{ default "" .Values.postgresql.auth.password }}@{{ default (printf "%s-%s" .Release.Name "postgresql") .Values.postgresql.host }}:{{ default "5432" .Values.postgresql.service.ports.postgresql }}/{{ default .Release.Name .Values.postgresql.auth.database }}"
  TRYTOND_ASYNC__CELERY: "amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@{{ .Release.Name }}-rabbitmq:{{ default "5672" .Values.rabbitmq.service.port }}"
  TRYTOND_ASYNC_CELERY: "amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@{{ .Release.Name }}-rabbitmq:{{ default "5672" .Values.rabbitmq.service.port }}" # duplicate of TRYTOND_ASYNC__CELERY
  TRYTOND_DOCUMENT_API__DOCUMENT_TOKEN_SECRET: {{ include "secret.token.documentTokenSecret" . }}
  {{- if not (and .Values.secrets .Values.secrets.backCore .Values.secrets.backCore.extraEnvVar .Values.secrets.backCore.extraEnvVar.TRYTOND_SESSION__PASSPHRASE) }}
  {{ include "secret.token.generator" (dict "key" "TRYTOND_SESSION__PASSPHRASE" "secretName" (printf "%s-backcore-configuration" (include "general.names.short" .)) "namespace" .Release.Namespace) }}
  {{- end }}
  {{- range $key, $value := (and .Values.secrets .Values.secrets.backCore .Values.secrets.backCore.extraEnvVar) }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

