apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s-backcore-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  TRYTOND_DATABASE__URI: "postgresql://{{ default "" .Values.postgresql.auth.username }}:{{ default "" .Values.postgresql.auth.password }}@{{ default (printf "%s-%s" .Release.Name "postgresql") .Values.postgresql.host }}:{{ default "5432" .Values.postgresql.service.ports.postgresql }}/{{ default .Release.Name .Values.postgresql.auth.database }}"
  TRYTOND_ASYNC__CELERY: "amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@{{ .Release.Name }}-rabbitmq:{{ .Values.rabbitmq.service.port }}"
  TRYTOND_ASYNC_CELERY: "amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@{{ .Release.Name }}-rabbitmq:{{ .Values.rabbitmq.service.port }}" # duplicate of TRYTOND_ASYNC__CELERY
  {{- range $key, $value := .Values.secrets.backCore.coog.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

