{{- if (and .Values.secrets .Values.secrets.extraEnvVar) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-global-configuration" (include "general.names.short" .) }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := (and .Values.secrets .Values.secrets.extraEnvVar) }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
