{{- if (or .Values.frontCore.enabled
          .Values.apiB2c.enabled
          .Values.apiReferential.enabled
          .Values.b2c.enabled
          .Values.b2b.enabled
          .Values.customerBackend.enabled
          .Values.customerFrontend.enabled)
-}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-frontcore-configuration" (include "general.names.short" .) }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  POSTGRESQL_URL: "postgresql://{{ coalesce .Values.postgresql.auth.api_user .Values.postgresql.auth.username "" }}:{{ coalesce .Values.postgresql.auth.api_password .Values.postgresql.auth.password "" }}@{{ default (printf "%s-%s" .Release.Name "postgresql") .Values.postgresql.host }}:{{ default "5432" .Values.postgresql.service.ports.postgresql }}/{{ default .Release.Name .Values.postgresql.auth.database }}"
  {{- if not (and .Values.secrets .Values.secrets.frontCore .Values.secrets.frontCore.extraEnvVar .Values.secrets.frontCore.extraEnvVar.JWT_INTERNAL_ENCRYPTION) }}
  {{ include "secret.token.generator" (dict "key" "JWT_INTERNAL_ENCRYPTION" "secretName" (printf "%s-frontcore-configuration" (include "general.names.short" .)) "namespace" .Release.Namespace) }}
  {{- end }}
  {{- range $key, $value := (and .Values.secrets .Values.secrets.frontCore .Values.secrets.frontCore.extraEnvVar) }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
