{{- if .Values.secrets.extraEnvVar }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-global-configuration" (include "general.names.short" .) }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  {{- if and (not .Values.secrets.extraEnvVar.JWT_ENCRYPTION) (not (lookup "v1" "Secret" .Release.Namespace "JWT_ENCRYPTION")) }}
  JWT_ENCRYPTION: {{ randAlphaNum 32 | quote }}
  {{- end }}
  {{- if not .Values.secrets.extraEnvVar.JWT_INTERNAL_ENCRYPTION }}
  {{ include "secret.token.generator" (dict "key" "JWT_INTERNAL_ENCRYPTION" "secretName" (printf "%s-global-configuration" (include "general.names.short" .)) "namespace" .Release.Namespace) }}
  {{- end }}
  {{- range $key, $value := .Values.secrets.extraEnvVar }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
