{{- if .Values.secrets.extraEnvVar }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s-global-configuration" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  {{- if not .Values.secrets.extraEnvVar.JWT_ENCRYPTION }}
  JWT_ENCRYPTION: {{ include "secret.token.generator" (dict "value" .Values.secrets.extraEnvVar.JWT_ENCRYPTION) | quote }}
  {{- end }}
  {{- if not .Values.secrets.extraEnvVar.JWT_INTERNAL_ENCRYPTION }}
  JWT_INTERNAL_ENCRYPTION: {{ include "secret.token.generator" (dict "value" .Values.secrets.extraEnvVar.JWT_INTERNAL_ENCRYPTION) | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secrets.extraEnvVar }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
