apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-postgresql" (include "general.names.short" .) }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  COOG_DB_USER: {{ default "" .Values.postgresql.auth.username | quote }}
  COOG_DB_PASSWORD: {{ default "" .Values.postgresql.auth.password | quote }}