{{- if (or .Values.frontCore.enabled
          .Values.apiB2c.enabled
          .Values.apiReferential.enabled
          .Values.b2c.enabled
          .Values.b2b.enabled
          .Values.customerBackend.enabled
          .Values.customerFrontend.enabled
          .Values.web.enabled)
-}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-mongodb-configuration" (include "general.names.short" .) }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.mongodb.auth.uri }}
  MONGODB_URI: {{ default (printf "mongodb://%s:%s@%s-mongodb:%d/%s" (first .Values.mongodb.auth.usernames) (first .Values.mongodb.auth.passwords) .Release.Name (.Values.mongodb.service.ports.mongodb | int) (first .Values.mongodb.auth.databases)) .Values.mongodb.auth.uri | quote }}
  {{- else }}
  MONGO_USER: {{ first .Values.mongodb.auth.usernames | quote }}
  MONGO_PASSWORD: {{ first .Values.mongodb.auth.passwords | quote }}
  {{- end }}
{{- end }}
