{{- if (or .Values.frontCore.enabled
          .Values.apiB2c.enabled
          .Values.apiReferential.enabled
          .Values.b2c.enabled
          .Values.b2b.enabled
          .Values.customerBackend.enabled
          .Values.customerFrontend.enabled
          .Values.web.enabled)
-}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s-mongodb" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_USER: {{ first .Values.mongodb.auth.usernames | quote }}
  MONGO_PASSWORD: {{ first .Values.mongodb.auth.passwords | quote }}
{{- end }}
