{{- if .Values.quota.enabled -}}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Name }}
spec:
  hard:
    requests.cpu: {{ .Values.quota.cpu_request }}
    requests.memory: {{ .Values.quota.memory_request }}
    limits.cpu: {{ .Values.quota.cpu_limit }}
    limits.memory: {{ .Values.quota.memory_limit }}
{{- end }}
