apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-configuration" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.postgresql.ismanaged }}
  TRYTOND_DATABASE__URI: "postgresql://{{ default "" .Values.postgresql.auth.username }}:{{ default "" .Values.postgresql.auth.password }}@{{ printf "%s-%s" .Release.Name "postgresql" }}:{{ default "5432" .Values.postgresql.service.ports.postgresql }}/{{ default .Release.Name .Values.postgresql.auth.database }}"
  {{- else }}
  TRYTOND_DATABASE__URI: "postgresql://{{ default "" .Values.postgresql.auth.username }}:{{ default "" .Values.postgresql.auth.password }}@{{ default "" .Values.postgresql.host }}:{{ default "5432" .Values.postgresql.service.ports.postgresql }}/{{ default .Release.Name .Values.postgresql.auth.database }}"
  {{- end }}
  TRYTOND_ASYNC__CELERY: "amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@{{ .Release.Name }}-rabbitmq:{{ .Values.rabbitmq.service.port }}"
  TRYTOND_SESSION__PASSPHRASE: {{ default "" .Values.secrets.coog.trytond_session__passphrase | quote }}
  {{- range $key, $value := .Values.secrets.coog }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

