{{- if .Values.api.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: coog-api-mongo-db-secret
  labels:
{{ include "chart_labels" . | indent 4 }}
type: Opaque
stringData:
  MONGODB_URI: {{ default (printf "mongodb://%s:%s@%s-mongodb:%d/%s" (.Values.mongodb.mongodbUsername) (.Values.secrets.gateway.mongodb_root_password) (.Release.Name) (.Values.mongodb.service.port | int) (.Values.api.mongodb.database)) .Values.secrets.api.mongodb_uri | quote }}
{{- end }}
