{{- if .Values.apiReferential.enabled -}}
{{- if .Values.secrets.apiReferential.config -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-configuration" (include "general.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.apiReferential.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
