{{- if .Values.b2c.enabled -}}
apiVersion: {{ include "general.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "general.names.fullname" . }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
  annotations:
  {{- if and .Values.ingress.thisTls.letsencrypt .Values.ingress.thisTls.enabled }}
    cert-manager.io/cluster-issuer: letsencrypt
  {{- end }}
  {{- if $.Values.maintenanceMode.enabled }}
    nginx.ingress.kubernetes.io/custom-http-errors: {{ .Values.maintenanceMode.ingress.nginx.customhttperrors }}
    nginx.ingress.kubernetes.io/default-backend: {{ printf "%s-maintenance" (include "general.names.short" .) }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ join "," (.Values.ingress.nginx.whiteList.trustedCidr) }}
  {{- range $key, $value := $.Values.maintenanceMode.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- else }}
  {{- if eq (default .Values.ingress.nginx.whiteList.managementMode .Values.b2c.ingress.nginx.whiteList.managementMode) "append" }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ join "," (concat .Values.ingress.nginx.whiteList.trustedCidr .Values.ingress.nginx.whiteList.publicCidr .Values.b2c.ingress.nginx.whiteList.publicCidr) | quote }}
  {{- else if eq (default .Values.ingress.nginx.whiteList.managementMode .Values.b2c.ingress.nginx.whiteList.managementMode) "replace" }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ join "," (concat .Values.ingress.nginx.whiteList.trustedCidr (default .Values.ingress.nginx.whiteList.publicCidr .Values.b2c.ingress.nginx.whiteList.publicCidr)) | quote }}
  {{- else }}
    nginx.ingress.kubernetes.io/whitelist-source-range: 127.0.0.1/32
  {{- end }}
  {{- end }}
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := .Values.b2c.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
{{- if and .Values.ingress.thisTls.enabled (or .Values.ingress.thisTls.letsencrypt .Values.ingress.host) }}
  tls:
    {{- if and .Values.ingress.thisTls.enabled .Values.ingress.thisTls.letsencrypt }}
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ printf "%s-tls" .Values.ingress.host }}
    {{- end }}
    {{- if .Values.ingress.thisTls.configuration }}
    {{- include "general.tplvalues.render" (dict "value" .Values.ingress.thisTls.configuration "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
        {{- range .Values.b2c.ingress.defaultPaths }}
        {{- if eq (include "general.ingress.apiVersion" $) "networking.k8s.io/v1" }}
        - path: {{ . | quote }}
          pathType: Prefix
          backend:
            service:
              name: {{ include "general.names.fullname" $ }}
              port:
                number: 80
        {{- else }}
        - path: {{ . | quote }}
          backend:
            servicename: {{ include "general.names.fullname" $ }}
            servicePort: 80
        {{- end }}
        {{- end }}
  {{- range .Values.b2c.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
        {{- if eq (include "general.ingress.apiVersion" $) "networking.k8s.io/v1" }}
        - path: {{ . | quote }}
          pathType: Prefix
          backend:
            service:
              name: {{ include "general.names.fullname" $ }}
              port:
                number: 80
        {{- else }}
        - path: {{ . | quote }}
          backend:
            servicename: {{ include "general.names.fullname" $ }}
            servicePort: 80
        {{- end }}
        {{- end }}
  {{- end }}
{{- end }}
