{{- if .Values.libroconv.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5000
      targetPort: http
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
{{- end }}
