stages:
  - lint
  - build
  - deploy
  - trigger

include:
  - project: "coopengo/devops/gitlab-ci-template"
    ref: master
    file:
      - "/Jobs/reference.debian.gitlab-ci.yml"
      - "/Jobs/reference.alpine.gitlab-ci.yml"
  - local: ".gitlab/.linter.gitlab-ci.yml"
    rules:
      - if: "$CI_PIPELINE_SOURCE =~ /^(web)$/"
      - changes:
          - ".gitlab/**/*.{yml,yaml}"
          - ".gitlab-ci.{yml,yaml}"
        when: "never"
      - changes:
          - "**/*.{yaml,yml}"
  - local: ".gitlab/.build.gitlab-ci.yml"
  - local: ".gitlab/.weekly-build.gitlab-ci.yml"
