stages:
  - lint
  - build
  - deploy
  - trigger

include:
  - project: "coopengo/devops/gitlab-ci-template"
    ref: master
    file:
      - "/Jobs/reference.debian.gitlab-ci.yml"
      - "/Jobs/reference.alpine.gitlab-ci.yml"
  - local: ".gitlab/.linter.gitlab-ci.yml"
    rules:
      - if: '$CI_PIPELINE_SOURCE == "web"'
      - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH'
        changes:
          - "**/*.yaml"
  - local: ".gitlab/.build.gitlab-ci.yml"
    rules:
      - if: '$CI_PIPELINE_SOURCE == "web"'
      - if: '$CI_PIPELINE_SOURCE =~ /^(schedule|trigger|pipeline)$/ && $CI_COMMIT_BRANCH =~ /^(master|coog-(([[:digit:]]{1,2}).([[:digit:]]{1,2})))$/'
      - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /^(master|coog-(([[:digit:]]{1,2}).([[:digit:]]{1,2})))$/'
        changes:
          - "**/Chart.yaml"

trigger:automatic-generation:
  stage: trigger
  image: bitnami/git
  script:
    - |-
      for BRANCH in $(git ls-remote --head "${CI_REPOSITORY_URL}" -l "coog-*" | cut -d '/' -f3 | grep -E '^(coog-[[:digit:]]{1,2}.[[:digit:]]{1,3})$' | sort -Vr | head -n 4)
      do
        curl -X POST \
          --fail \
          -F "token=${CI_JOB_TOKEN}" \
          -F "ref=${BRANCH}" \
          https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/trigger/pipeline
      done
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
