synchronize:pipeline:
  stage: synchronize
  image: bitnami/git
  before_script:
    - !reference [.git_with_ssh:debian, before_script]
    - git remote set-url origin git@${CI_SERVER_HOST}:${CI_PROJECT_PATH}.git
    - git fetch --all
  script:
    - |-
      for BRANCH in $(git ls-remote --refs -h origin -l "coog-*" | cut -s -d '/' -f3 | grep -E "^(coog-[[:digit:]]{1,2}).([[:digit:]]{1,2})$" )
      do
        git checkout "${BRANCH}"
        git checkout "${CI_COMMIT_SHORT_SHA}" .gitlab-ci.yml README.md .gitlab/
        git commit -m "Merge .gitlab-ci.yml, REAMDME.md and .gitlab/ from \"${CI_COMMIT_SHORT_SHA}\""
      done
      git push --all
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes:
        - ".gitlab-ci.yml"
        - "README.md"
        - ".gitlab/**/*"