trigger:weekly-build:
  stage: trigger
  image: bitnami/git
  script:
    - apt update
    - apt install -y curl
    - |-
      for BRANCH in $(git ls-remote --head "${CI_REPOSITORY_URL}" | cut -d '/' -f3 | grep -E '^(master|coog-[[:digit:]]{1,2}.[[:digit:]]{1,3})$' | sort -Vr | head -n 5)
      do
        echo "Working on ${BRANCH}..."
        echo " "
        curl -X POST \
          --fail \
          -F "token=${CI_TRIGGER_TOKEN}" \
          -F "ref=${BRANCH}" \
          -F "variables[WEEKLY_BUILD]=true" \
          -F "variables[MINOR_VERSION]=${MINOR_VERSION:-0}" \
          "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/trigger/pipeline"
      done
  rules:
    - if: '$CI_PIPELINE_SOURCE =~ /^(schedule)$/ && $WEEKLY_BUILD && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

package:weekly-build:
  stage: package
  image: bitnami/git
  before_script:
    - !reference [.git_with_ssh:debian, before_script]
    - git remote set-url origin git@${CI_SERVER_HOST}:${CI_PROJECT_PATH}.git
    - |-
      if [[ ${MINOR_VERSION} =~ ^(([[:digit:]]{4})(.[[:digit:]]{1,2})?)$ ]]; then
        if [[ ${CI_COMMIT_BRANCH} == "${CI_DEFAULT_BRANCH}" ]]; then
          VERSION="$(echo "$MINOR_VERSION" | grep -Eo "([[:digit:]]{4})" | sed 's/\(.\{2\}\)/\1./g; s/.$//').${MINOR_VERSION}"
        else
          VERSION="${CI_COMMIT_BRANCH#coog-}.${MINOR_VERSION}"
        fi
      else
        if [[ ${CI_COMMIT_BRANCH} == "${CI_DEFAULT_BRANCH}" ]]; then
          VERSION="$(date +%y.%V.%y%V)"
        else
          VERSION="${CI_COMMIT_BRANCH#coog-}.$(date +%y%V)"
        fi
      fi
      echo "Version to generate: ${VERSION}"
  script:
    - |-
      for HELM_PROJECT in $(find . -mindepth 1 -maxdepth 1 -type d ! -name ".git" -exec basename {} \;)
      do
        if [ -f "${CI_PROJECT_DIR}/${HELM_PROJECT}/Chart.yaml" ]
        then
          git checkout ${CI_COMMIT_BRANCH}
          sed -i "/version: /c\version: \'${VERSION}\'" "${CI_PROJECT_DIR}/${HELM_PROJECT}/Chart.yaml"
        fi
      done
    - git commit -am "Packaging ${VERSION}" || echo "Nothing to commit"
    - git push
  rules:
    - if: '$WEEKLY_BUILD && $CI_PIPELINE_SOURCE =~ /^(trigger|pipeline)$/'
