{{- if (or .Values.frontCore.enabled
          .Values.apiB2c.enabled
          .Values.apiReferential.enabled
          .Values.b2c.enabled
          .Values.b2b.enabled
          .Values.customerBackend.enabled
          .Values.customerFrontend.enabled)
-}}
{{- if .Values.frontCore.apiIdentityManager.extraEnvVar -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-configuration" (include "general.names.fullname" .) }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.frontCore.apiIdentityManager.extraEnvVar }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
