{{- if (or .Values.frontCore.enabled
          .Values.apiB2c.enabled
          .Values.apiReferential.enabled
          .Values.b2c.enabled
          .Values.b2b.enabled
          .Values.customerBackend.enabled
          .Values.customerFrontend.enabled)
-}}
{{- if or .Values.podDisruptionBudget .Values.frontCore.apiIdentityManager.podDisruptionBudget }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ printf "%s-api-identity-manager" (include "general.names.short" .) }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "general.labels.matchLabels" . | nindent 6 }}
  {{- if or .Values.podDisruptionBudget.minAvailable .Values.frontCore.apiIdentityManager.podDisruptionBudget.minAvailable }}
  minAvailable: {{ default .Values.podDisruptionBudget.minAvailable .Values.frontCore.apiIdentityManager.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if or .Values.podDisruptionBudget.maxUnavailable .Values.frontCore.apiIdentityManager.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ default .Values.podDisruptionBudget.maxUnavailable .Values.frontCore.apiIdentityManager.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
{{- end }} 