{{- if .Values.maintenanceMode.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "general.names.fullname" . }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "general.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "general.labels.standard" . | nindent 8 }}
      {{- if (or .Values.extraEnvVar (and .Values.maintenanceMode .Values.maintenanceMode.extraEnvVar) (and .Values.secrets .Values.secrets.extraEnvVar)) }}
      annotations:
        {{- if .Values.extraEnvVar }}
        checksum/configmap-global: {{ include (printf "%s/%s" $.Template.BasePath "configmap-global.yaml") . | sha256sum  }}
        {{- end }}
        {{- if (and .Values.maintenanceMode .Values.maintenanceMode.extraEnvVar) }}
        checksum/configmap: {{ include (printf "%s/%s/%s" $.Template.BasePath (base (dir .Template.Name)) "configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if (and .Values.secrets .Values.secrets.extraEnvVar) }}
        checksum/secret-global: {{ include (printf "%s/%s" $.Template.BasePath "secret-global.yaml") . | sha256sum  }}
        {{- end }}
      {{- end }}
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        procMount: Default
        runAsNonRoot: true
      imagePullSecrets:
        - name: {{ (default "docker-registry" (and .Values.imageCredentials .Values.imageCredentials.name)) }}
      containers:
        - name: {{ include "general.names.name" . }}
          image: "{{ default .Values.image.repository .Values.maintenanceMode.image.repository }}/{{ .Values.maintenanceMode.image.name }}:{{ default .Values.image.tag .Values.maintenanceMode.image.tag }}"
          imagePullPolicy: {{ default .Values.image.pullPolicy .Values.maintenanceMode.image.pullPolicy | quote }}
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            procMount: Default
            runAsNonRoot: true
          {{- if (or .Values.extraEnvVar (and .Values.maintenanceMode .Values.maintenanceMode.extraEnvVar) (and .Values.secrets .Values.secrets.extraEnvVar)) }}
          envFrom:
            {{- if .Values.extraEnvVar }}
            - configMapRef:
                name: {{ printf "%s-global-configuration" (include "general.names.short" .) }}
            {{- end }}
            {{- if (and .Values.maintenanceMode .Values.maintenanceMode.extraEnvVar) }}
            - configMapRef:
                name: {{ printf "%s-configuration" (include "general.names.fullname" .) }}
            {{- end }}
            {{- if (and .Values.secrets .Values.secrets.extraEnvVar) }}
            - secretRef:
                name: {{ printf "%s-global-configuration" (include "general.names.short" .) }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
          resources: {{- toYaml .Values.maintenanceMode.resources | nindent 12 }}
      {{- with default .Values.nodeSelector .Values.maintenanceMode.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with default .Values.affinity .Values.maintenanceMode.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with default .Values.tolerations .Values.maintenanceMode.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if default .Values.dnsPolicy .Values.maintenanceMode.dnsPolicy }}
      dnsPolicy: {{ default .Values.dnsPolicy .Values.maintenanceMode.dnsPolicy }}
      {{- end }}
      {{- if default .Values.dnsConfig .Values.maintenanceMode.dnsConfig }}
      dnsConfig: {{- toYaml default .Values.dnsConfig .Values.maintenanceMode.dnsConfig | indent 8 }}
      {{- end }}
{{- end }}
