apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s-postgresql" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  COOG_DB_USER: {{ default "" .Values.postgresql.auth.username | quote }}
  COOG_DB_PASSWORD: {{ default "" .Values.postgresql.auth.password | quote }}