{{- if (or .Values.frontCore.enabled
          .Values.apiB2c.enabled
          .Values.apiReferential.enabled
          .Values.b2c.enabled
          .Values.b2b.enabled
          .Values.customerBackend.enabled
          .Values.customerFrontend.enabled
          .Values.web.enabled)
-}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-configuration" (include "general.names.fullname" .) }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  {{- if not (and .Values.secrets .Values.secrets.frontCore .Values.secrets.frontCore.gateway .Values.secrets.frontCore.gateway.extraEnvVar.COOG_WEB_TOKEN) }}
  {{ include "secret.token.generator" (dict "key" "COOG_WEB_TOKEN" "secretName" (printf "%s-configuration" (include "general.names.fullname" .)) "namespace" .Release.Namespace) }}
  {{- end }}
  {{- range $key, $value := (and .Values.secrets .Values.secrets.frontCore .Values.secrets.frontCore.gateway .Values.secrets.frontCore.gateway.extraEnvVar) }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
