apiVersion: v1
kind: Secret
metadata:
  name: {{ include "full_name" . }}-mongo-db-secret
  labels:
{{ include "chart_labels" . | indent 4 }}
type: Opaque
stringData:
  USER: {{ .Values.gateway.mongodb_user | quote }}
  PASSWORD: {{ .Values.gateway.mongodb_root_password | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "full_name" . }}-coog-web-secret
  labels:
{{ include "chart_labels" . | indent 4 }}
type: Opaque
stringData:
  GATEWAY_TOKEN: {{ .Values.gateway.coog_web_token | quote }}
  {{- if .Values.gateway.forcedotcom_client_id }}
  FORCEDOTCOM_CLIENT_ID: {{ .Values.gateway.forcedotcom_client_id | quote }}
  {{- end }}
  {{- if .Values.gateway.forcedotcom_client_secret }}
  FORCEDOTCOM_CLIENT_SECRET: {{ .Values.gateway.forcedotcom_client_secret | quote }}
  {{- end }}