{{- if .Values.libroconv.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ default .Values.replicaCount .Values.libroconv.replicaCount }}
  strategy:
  {{- if not .Values.quota.rollingUpdate }}
    type: Recreate
  {{- else -}}
    type: {{ default .Values.strategy.type .Values.libroconv.strategy.type }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
    spec:
    {{- with .Values.image.pullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ include "common.names.name" . }}
          image: "{{ default .Values.image.repository .Values.libroconv.image.repository }}/{{ .Values.libroconv.image.name }}:{{ default .Values.image.tag .Values.libroconv.image.tag }}"
          imagepullPolicy: {{ default .Values.image.pullPolicy .Values.libroconv.image.pullPolicy | quote }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            procMount: Default
            runAsNonRoot: true
            runAsUser: {{ default .Values.securityContext.runAsUser .Values.libroconv.securityContext.runAsUser }}
          ports:
            - name: http
              containerPort: 5000
          startupProbe: {{- toYaml (default .Values.startupProbe .Values.libroconv.startupProbe) | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /liveness
              port: http
            {{- toYaml (default .Values.livenessProbe .Values.libroconv.livenessProbe) | nindent 12 }}
          readinessProbe:
            httpGet:
              path: "/liveness"
              port: http
            {{- toYaml (default .Values.readinessProbe .Values.libroconv.readinessProbe) | nindent 12 }}
          resources: {{- toYaml .Values.libroconv.resources | nindent 12 }}
      {{- with default .Values.nodeSelector .Values.libroconv.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with default .Values.affinity .Values.libroconv.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with default .Values.tolerations .Values.libroconv.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if default .Values.dnsPolicy .Values.libroconv.dnsPolicy }}
      dnsPolicy: {{ default .Values.dnsPolicy .Values.libroconv.dnsPolicy }}
      {{- end }}
      {{- if default .Values.dnsConfig .Values.libroconv.dnsConfig }}
      dnsConfig: {{- toYaml default .Values.dnsConfig .Values.libroconv.dnsConfig | indent 8 }}
      {{- end }}
{{- end }}
