{{- if (or .Values.b2c.enabled
          .Values.customerBackend.enabled
          .Values.customerFrontend.enabled)
-}}
{{- if or .Values.podDisruptionBudget .Values.apiB2c.podDisruptionBudget }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "general.names.fullname" . }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "general.labels.matchLabels" . | nindent 6 }}
  {{- if or .Values.podDisruptionBudget.minAvailable .Values.apiB2c.podDisruptionBudget.minAvailable }}
  minAvailable: {{ default .Values.podDisruptionBudget.minAvailable .Values.apiB2c.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if or .Values.podDisruptionBudget.maxUnavailable .Values.apiB2c.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ default .Values.podDisruptionBudget.maxUnavailable .Values.apiB2c.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
{{- end }}
