{{- if (or .Values.b2c.enabled
          .Values.customerBackend.enabled
          .Values.customerFrontend.enabled)
-}}
{{- if .Values.secrets.apiB2c.config -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-configuration" (include "general.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.apiB2c.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
