{{- if or .Values.web.enabled .Values.b2b.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-configuration" (include "general.names.fullname" .) }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  COOG_API_MONGO_USER: {{ first .Values.mongodb.auth.usernames | quote }}
  COOG_API_MONGO_PASSWORD: {{ first .Values.mongodb.auth.passwords | quote }}
{{- end }}
