{{- if or .Values.web.enabled .Values.b2b.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-configuration" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  COOG_API_MONGO_USER: {{ .Values.mongodb.auth.username | quote }}
  COOG_API_MONGO_PASSWORD: {{ .Values.mongodb.auth.password | quote }}
{{- end }}
