{{- if or .Values.web.enabled .Values.b2b.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ default .Values.replicaCount .Values.web.replicaCount }}
  strategy:
  {{- if not .Values.quota.rollingUpdate }}
    type: Recreate
  {{- else -}}
    type: {{ default .Values.strategy.type .Values.web.strategy.type }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
    spec:
    {{- with .Values.image.pullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ include "common.names.name" . }}
          image: "{{ default .Values.image.repository .Values.web.image.repository }}/{{ .Values.web.image.name }}:{{ default .Values.image.tag .Values.web.image.tag }}"
          imagepullPolicy: {{ default .Values.image.pullPolicy .Values.web.image.pullPolicy | quote }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            procMount: Default
            runAsNonRoot: true
            runAsUser: {{ default .Values.securityContext.runAsUser .Values.web.securityContext.runAsUser }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-configuration" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
            - secretRef:
                name: {{ printf "%s-mongodb" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
          ports:
            - name: http
              containerPort: 3000
          startupProbe: {{- toYaml (default .Values.startupProbe .Values.web.startupProbe) | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /auth
              port: http
            exec:
            {{- toYaml (default .Values.livenessProbe .Values.web.livenessProbe) | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /auth
              port: http
            {{- toYaml (default .Values.readinessProbe .Values.web.readinessProbe) | nindent 12 }}
          resources: {{- toYaml .Values.web.resources | nindent 12 }}
      {{- with default .Values.nodeSelector .Values.web.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with default .Values.affinity .Values.web.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with default .Values.tolerations .Values.web.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if default .Values.dnsPolicy .Values.web.dnsPolicy }}
      dnsPolicy: {{ default .Values.dnsPolicy .Values.web.dnsPolicy }}
      {{- end }}
      {{- if default .Values.dnsConfig .Values.web.dnsConfig }}
      dnsConfig: {{- toYaml default .Values.dnsConfig .Values.web.dnsConfig | indent 8 }}
      {{- end }}
{{- end }}
