apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flower.fullname" . }}
  labels:
{{ include "flower.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "flower.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "flower.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "flower.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/local/bin/python
            - /usr/local/bin/flower
            - --debug=True
            - --address=0.0.0.0
            - --url_prefix=flower
          {{- with .Values.args }}
          args:
          {{- range . }}
            - {{ . | quote }}
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.internalPort }}
{{/*          livenessProbe:*/}}
{{/*            failureThreshold: 10*/}}
{{/*            httpGet:*/}}
{{/*              path: /*/}}
{{/*              port: {{ .Values.service.internalPort }}*/}}
{{/*            initialDelaySeconds: 10*/}}
{{/*            periodSeconds: 5*/}}
{{/*          readinessProbe:*/}}
{{/*            failureThreshold: 10*/}}
{{/*            httpGet:*/}}
{{/*              path: /*/}}
{{/*              port: {{ .Values.service.internalPort }}*/}}
{{/*            initialDelaySeconds: 10*/}}
{{/*            periodSeconds: 5*/}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: CELERY_BROKER_URL
              value: {{ .Values.celeryBrokerUrl }}
            - name: FLOWER_URL_PREFIX
              value: {{ .Values.urlPrefix }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
